### ISSUE TITLE
routing url pattern not working

### ISSUE THREAD

**Issue by devalexqt** [aaronwlee/Attain#14]
Looks line this not working then I request from browser: `/js/index.js` but if i just simple request `/js` then working first middleware.
```
app.use("/js",(req,res)=>{...});
```
or
```
app.use("/js*",(req,res)=>{...});
```

**Comment by aaronwlee** [comment]
you can try with
```
app.use("/js(.*)",(req,res)=>{...});
```
I'm using [path-to-regex](https://github.com/pillarjs/path-to-regexp) for identifying the path. I'll take a look at how to enhance it.

**Comment by devalexqt** [comment]
Yes this working!
Can it accept array of paths: ["/js","/script", ....] ?

**Comment by aaronwlee** [comment]
now it's working as like "/js*"
but as far as we have middlewares, I will not support the array of paths
thx :)

**Comment by devalexqt** [comment]
Not workin, got error:
```
 TypeError: Unexpected MODIFIER at 3, expected END
    at mustConsume (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:157:11)
    at parse (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:228:5)
    at stringToRegexp (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:494:25)
    at pathToRegexp (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:616:10)
    at checkPathAndParseURLParams (https://deno.land/x/attain/utils.ts:17:23)
    at App.attainProcedure (https://deno.land/x/attain/application.ts:32:15)
    at async App.handleRequest (https://deno.land/x/attain/application.ts:97:7)
```

**Comment by aaronwlee** [comment]
can you show me the debug mode log?

**Comment by devalexqt** [comment]
Looks like both "/js" and "/js*" not working. 
```
DEBUG JS - args []
DEBUG JS - sendAsync op_connect [33m35[39m
DEBUG JS - sendAsync op_connect [33m35[39m
[36mAttain FrameWork[39m [34mv0.7[39m - [32mReady![39m
DEBUG JS - sendSync op_listen [33m37[39m
DEBUG JS - sendAsync op_accept [33m34[39m
http://localhost:8000
DEBUG JS - sendAsync op_accept [33m34[39m
==>>>>>>>>>>>>>>.ws session: 023eb900-bf43-4205-bbd1-5cb7899e39c3
socket connected!
==>REDIS SUBSCRIBER LISTEN....
DEBUG JS - sendAsync op_accept [33m34[39m
DEBUG JS - sendAsync op_accept [33m34[39m
==>sampleMiddleware session: 023eb900-bf43-4205-bbd1-5cb7899e39c3 , path: /js/index.js
DEBUG JS - sendSync op_apply_source_map [33m5[39m
DEBUG JS - sendSync op_apply_source_map [33m5[39m
DEBUG JS - sendSync op_apply_source_map [33m5[39m
DEBUG JS - sendSync op_apply_source_map [33m5[39m
DEBUG JS - sendSync op_apply_source_map [33m5[39m
DEBUG JS - sendSync op_apply_source_map [33m5[39m
DEBUG JS - sendSync op_apply_source_map [33m5[39m
TypeError: Unexpected MODIFIER at 3, expected END
    at mustConsume (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:157:11)
    at parse (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:228:5)
    at stringToRegexp (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:494:25)
    at pathToRegexp (https://raw.githubusercontent.com/pillarjs/path-to-regexp/master/src/index.ts:616:10)
    at checkPathAndParseURLParams (https://deno.land/x/attain/utils.ts:17:23)
    at App.attainProcedure (https://deno.land/x/attain/application.ts:32:15)
    at async App.handleRequest (https://deno.land/x/attain/application.ts:97:7)
[32mGET[39m [36m500[39m /js/index.js - [1m47[22mms
```

**Comment by aaronwlee** [comment]
hum sorry can you show me that the log from here?
```
app.listen({port: 1231, debug: true})
```

**Comment by aaronwlee** [comment]
sorry, I found the reason and fixed it. it's my bad. XD

**Comment by devalexqt** [comment]
Thanks, now working.
Will be testing more tomorrow.

Thanks for fixing.
