### ISSUE TITLE
v0.8 not working

### ISSUE THREAD

**Issue by devalexqt** [aaronwlee/Attain#21]
```
error: Uncaught BadResource: Bad resource ID 
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async Object.copy ($deno$/io.ts:64:20)
    at async writeResponse (https://deno.land/std/http/_io.ts:264:15)
    at async ServerRequest.respond (https://deno.land/std/http/server.ts:88:7)
    at async Process.finalize (https://deno.land/x/attain/process.ts:92:7)
    at async App.handleRequest (https://deno.land/x/attain/application.ts:18:5)
```

**Comment by aaronwlee** [comment]
it's working in 0.9 :) thx

0.9 version has a lot of enhancement such as better performance, and less memory consumption.

**Comment by devalexqt** [comment]
```
TypeError: Cannot read property 'pathname' of undefined
    at attainProcedure (https://deno.land/x/attain/process.ts:35:32)
    at attainProcedure (https://deno.land/x/attain/process.ts:49:21)
    at async Process (https://deno.land/x/attain/process.ts:12:5)
```

**Comment by aaronwlee** [comment]
This is too bad, 

the test file and procedure are really urgent...

Thanks for always helping me

**Comment by devalexqt** [comment]
thanks for fixing

**Comment by devalexqt** [comment]
Any news?
