### ISSUE TITLE
error: TS2502 [ERROR]:

### ISSUE THREAD

**Issue by malaxmimdkm** [aaronwlee/Attain#40]
error: TS2502 [ERROR]: 'thisArg' is referenced directly or indirectly in its own type annotation.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:22

TS2577 [ERROR]: Return type annotation circularly references itself.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                                                     ~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:54

TS2339 [ERROR]: Property 'transpileOnly' does not exist on type 'typeof Deno'.
      const result = await Deno.transpileOnly({
                                ~~~~~~~~~~~~~
    at https://deno.land/x/attain@1.1.1/viewEngine/ReactCompiler.ts:118:33

Found 3 errors.

**Comment by dcj9** [comment]
error: TS2502 [ERROR]: 'thisArg' is referenced directly or indirectly in its own type annotation.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:22

**Comment by aaronwlee** [comment]
@dcj9 which code makes you reach that error message?
